/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.view;

import controller.Controller;
import entity.Broj;
import entity.Delegat;
import entity.Mesto;
import entity.Ulica;
import entity.ZaposlenostStatusEnum;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AddDelegatForm extends javax.swing.JFrame {

    /**
     * Creates new form AddDelegatForm
     */
    DelegatiForm parent;

    public AddDelegatForm(DelegatiForm parent) {
        initComponents();
        this.parent = parent;
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJmbg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBroj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbMesto = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtOpstina = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cmbUlica = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cmbZaposlenost = new javax.swing.JComboBox();
        addUlicaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Unesite podatke za novog delegata:");

        txtPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeActionPerformed(evt);
            }
        });

        jLabel2.setText("Ime:");

        jLabel3.setText("Prezime:");

        jLabel4.setText("JMBG:");

        txtJmbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmbgActionPerformed(evt);
            }
        });

        jLabel5.setText("Adresa");

        txtBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojActionPerformed(evt);
            }
        });

        jLabel6.setText("Broj:");

        jLabel7.setText("Ulica:");

        jLabel8.setText("Grad:");

        jLabel9.setText("Opstina:");

        txtOpstina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpstinaActionPerformed(evt);
            }
        });

        btnSave.setText("SACUVAJ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel10.setText("Zaposlenost:");

        addUlicaBtn.setText("+");
        addUlicaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUlicaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbUlica, 0, 138, Short.MAX_VALUE)
                                    .addComponent(cmbMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addUlicaBtn)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOpstina, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtJmbg, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(cmbZaposlenost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(20, 20, 20)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbZaposlenost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtOpstina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cmbUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUlicaBtn))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private void txtJmbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmbgActionPerformed

    private void txtBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojActionPerformed

    private void txtOpstinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpstinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpstinaActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtIme.getText() == null || txtIme.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite ime delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txtPrezime.getText() == null || txtPrezime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite prezime delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txtJmbg.getText() == null || txtJmbg.getText().isEmpty() || txtJmbg.getText().length() != 13 || !txtJmbg.getText().chars().allMatch(Character::isDigit)) {
            JOptionPane.showMessageDialog(this, "Unesite validan jmbg delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (cmbZaposlenost.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Unesite validan status zaposlenja delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txtBroj.getText() == null || txtBroj.getText().isEmpty() || cmbUlica.getSelectedIndex() == -1 || cmbMesto.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Unesite validnu adresu delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String vrednost = txtBroj.getText();

        Broj broj = new Broj();
        broj.setVrednost(vrednost.trim());
        Ulica ulica = (Ulica) cmbUlica.getSelectedItem();

        broj.setUlica(ulica);
        try {
            broj = Controller.getInstance().getBrojByVrednost(broj);

            if (broj == null) {
                broj = new Broj();
                broj.setVrednost(vrednost);
                broj.setUlica(ulica);
                broj = Controller.getInstance().createBroj(broj);

                if (broj == null || broj.getIdBroj() == null) {
                    JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom cuvanja nove adrese", "", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            Delegat delegat = new Delegat();
            delegat.setImePrezime(txtIme.getText().trim() + " " + txtPrezime.getText().trim());
            delegat.setJmbg(txtJmbg.getText().trim());
            delegat.setBroj(broj);
            delegat.setZaposlenostStatus((ZaposlenostStatusEnum) cmbZaposlenost.getSelectedItem());

            delegat = Controller.getInstance().createDelegat(delegat);
            if (delegat != null && delegat.getIdDelegat() != null) {
                this.dispose();
                parent.prepareForm();
            } else {
                JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom cuvanja novog delegata", "", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            Logger.getLogger(AddDelegatForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void addUlicaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUlicaBtnActionPerformed
        Mesto mesto = (Mesto) cmbMesto.getSelectedItem();
        if (mesto == null || mesto.getNaziv() == null || mesto.getOpstina() == null || mesto.getOpstina().getNaziv() == null) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom ucitavanja opstine i grada", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new AddUlicaForm(this, true, (Mesto) cmbMesto.getSelectedItem()).setVisible(true);
    }//GEN-LAST:event_addUlicaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    private void prepareForm() {
        fillCmbZaposlenost();
        fillCmbGrad();
        txtOpstina.setEditable(false);
        addUlicaBtn.setEnabled(false);
    }

    private void fillCmbZaposlenost() {
        cmbZaposlenost.setModel(new DefaultComboBoxModel<>(ZaposlenostStatusEnum.values()));
        cmbZaposlenost.setSelectedIndex(-1);
    }

    private void fillCmbGrad() {
        List<Mesto> gradovi = new ArrayList<>();

        try {
            gradovi = Controller.getInstance().getMesto(new Mesto());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        cmbMesto.setModel(new DefaultComboBoxModel<>(gradovi.toArray(new Mesto[0])));
        cmbMesto.setSelectedIndex(-1);

        cmbMesto.addActionListener(e -> {
            Mesto selektovano = (Mesto) cmbMesto.getSelectedItem();
            if (selektovano != null && selektovano.getOpstina() != null) {
                txtOpstina.setText(selektovano.getOpstina().getNaziv());

                fillCmbUlica(selektovano);
            }
        });

        cmbUlica.addActionListener(e -> {
            if (cmbUlica.getSelectedIndex() != -1) {
                addUlicaBtn.setEnabled(true);
            } else {
                addUlicaBtn.setEnabled(false);
            }
        });
    }

    private void fillCmbUlica(Mesto selektovano) {
        List<Ulica> ulice = new ArrayList<>();
        try {
            Ulica ulica = new Ulica();
            ulica.setMesto(selektovano);

            ulice = Controller.getInstance().getUlicaWithMestoCondition(ulica);

            cmbUlica.setModel(new DefaultComboBoxModel<>(ulice.toArray(new Ulica[0])));
            cmbUlica.setSelectedIndex(-1);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        if (ulice == null || ulice.isEmpty()) {
            addUlicaBtn.setEnabled(true);
        }
    }

    public void reloadUlice(Mesto selektovano) {
        fillCmbUlica(selektovano);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUlicaBtn;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbMesto;
    private javax.swing.JComboBox cmbUlica;
    private javax.swing.JComboBox cmbZaposlenost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBroj;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtOpstina;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
