/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.view;

import controller.Controller;
import entity.Broj;
import entity.Delegat;
import entity.Mesto;
import entity.Ulica;
import entity.ZaposlenostStatusEnum;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DetailsDelegatForm extends javax.swing.JFrame {

    /**
     * Creates new form DetailsDelegatForm
     */
    DelegatiForm parent;
    Delegat delegat;

    public DetailsDelegatForm(DelegatiForm parent, Delegat delegat) {
        initComponents();
        this.parent = parent;
        this.delegat = delegat;
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIme = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbUlica = new javax.swing.JComboBox();
        txtJmbg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbZaposlenost = new javax.swing.JComboBox();
        txtBroj = new javax.swing.JTextField();
        addUlicaBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        cmbMesto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtOpstina = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("JMBG:");

        txtJmbg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmbgActionPerformed(evt);
            }
        });

        jLabel10.setText("Zaposlenost:");

        jLabel5.setText("Adresa");

        txtBroj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrojActionPerformed(evt);
            }
        });

        addUlicaBtn.setText("+");
        addUlicaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUlicaBtnActionPerformed(evt);
            }
        });

        jLabel6.setText("Broj:");

        jLabel7.setText("Ulica:");

        jLabel8.setText("Grad:");

        txtPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeActionPerformed(evt);
            }
        });

        jLabel2.setText("Ime:");

        jLabel9.setText("Opstina:");

        jLabel3.setText("Prezime:");

        txtOpstina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpstinaActionPerformed(evt);
            }
        });

        btnDelete.setText("OBRISI");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setText("SACUVAJ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("IZMENI");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbUlica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(addUlicaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOpstina, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJmbg)
                                    .addComponent(cmbZaposlenost, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEdit)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbZaposlenost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtOpstina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cmbUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUlicaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJmbgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmbgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmbgActionPerformed

    private void txtBrojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrojActionPerformed

    private void addUlicaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUlicaBtnActionPerformed
        Mesto mesto = (Mesto) cmbMesto.getSelectedItem();
        if (mesto == null || mesto.getNaziv() == null || mesto.getOpstina() == null || mesto.getOpstina().getNaziv() == null) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom ucitavanja opstine i grada", "", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new AddUlicaForm(this, true, (Mesto) cmbMesto.getSelectedItem()).setVisible(true);
    }//GEN-LAST:event_addUlicaBtnActionPerformed

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private void txtOpstinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOpstinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOpstinaActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        txtIme.setEditable(true);
        txtPrezime.setEditable(true);
        txtJmbg.setEditable(true);
        txtBroj.setEditable(true);
        cmbZaposlenost.setEnabled(true);
        cmbMesto.setEnabled(true);
        cmbUlica.setEnabled(true);
        btnSave.setVisible(true);
        btnDelete.setVisible(true);
        addUlicaBtn.setVisible(false);
        btnEdit.setVisible(false);
        addUlicaBtn.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int result = JOptionPane.showConfirmDialog(
                null,
                "Da li ste sigurni da zelite da izbrisete delegata?",
                "Potvrda brisanja",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (result == JOptionPane.YES_OPTION) {
            try {
                Controller.getInstance().deleteDelegat(delegat);
                JOptionPane.showMessageDialog(this, "Delegat je izbrisan", "", JOptionPane.INFORMATION_MESSAGE);
                parent.reloadTable();
                this.dispose();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom brisanja delegata", "Greska", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Delegat updateDelegat = new Delegat();
        updateDelegat.setIdDelegat(delegat.getIdDelegat());

        if (txtIme.getText() == null || txtIme.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite ime delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txtPrezime.getText() == null || txtPrezime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite prezime delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txtJmbg.getText() == null || txtJmbg.getText().isEmpty() || txtJmbg.getText().length() != 13 || !txtJmbg.getText().chars().allMatch(Character::isDigit)) {
            JOptionPane.showMessageDialog(this, "Unesite validan jmbg delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (cmbZaposlenost.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Unesite validan status zaposlenja delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (txtBroj.getText() == null || txtBroj.getText().isEmpty() || cmbUlica.getSelectedIndex() == -1 || cmbMesto.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Unesite validnu adresu delegata", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String vrednost = txtBroj.getText();
        updateDelegat.setBroj(delegat.getBroj());

        if (!txtOpstina.getText().trim().equals(delegat.getBroj().getUlica().getMesto().getOpstina().getNaziv())
                || !((Mesto) cmbMesto.getSelectedItem()).getNaziv().equals(delegat.getBroj().getUlica().getMesto().getNaziv())
                || !((Ulica) cmbUlica.getSelectedItem()).getNaziv().equals(delegat.getBroj().getUlica().getNaziv())
                || !vrednost.equals(delegat.getBroj().getVrednost())) {
            Broj broj = new Broj();
            broj.setVrednost(vrednost.trim());
            Ulica ulica = (Ulica) cmbUlica.getSelectedItem();

            broj.setUlica(ulica);

            try {
                broj = Controller.getInstance().getBrojByVrednost(broj);

                if (broj == null) {
                    broj = new Broj();
                    broj.setVrednost(vrednost);
                    broj.setUlica(ulica);
                    broj = Controller.getInstance().createBroj(broj);
                    updateDelegat.setBroj(broj);

                    if (broj == null || broj.getIdBroj() == null) {
                        JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom cuvanja nove adrese", "", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } else {
                    updateDelegat.setBroj(broj);
                }
            } catch (Exception ex) {
                Logger.getLogger(DetailsDelegatForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        updateDelegat.setImePrezime(txtIme.getText().trim() + " " + txtPrezime.getText().trim());
        updateDelegat.setJmbg(txtJmbg.getText().trim());

        updateDelegat.setZaposlenostStatus(
                (ZaposlenostStatusEnum) cmbZaposlenost.getSelectedItem());
        try {
            updateDelegat = Controller.getInstance().updateDelegat(updateDelegat);

            if (updateDelegat != null) {
                JOptionPane.showMessageDialog(this, "Delegat je uspesno azuriran");
                delegat = updateDelegat;
                parent.reloadTable();
                prepareForm();
            }
        } catch (Exception ex) {
            Logger.getLogger(DetailsDelegatForm.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    private void prepareForm() {
        btnEdit.setVisible(true);
        btnSave.setVisible(false);
        btnDelete.setVisible(false);
        addUlicaBtn.setVisible(false);
        String[] ime_prezime = delegat.getImePrezime().split(" ");
        txtIme.setText(ime_prezime[0]);
        txtIme.setEditable(false);
        txtPrezime.setText(ime_prezime[1]);
        txtPrezime.setEditable(false);
        txtJmbg.setText(delegat.getJmbg());
        txtJmbg.setEditable(false);
        cmbZaposlenost.setEnabled(false);
        txtBroj.setText(delegat.getBroj().getVrednost());
        txtBroj.setEditable(false);
        txtOpstina.setText(delegat.getBroj().getUlica().getMesto().getOpstina().getNaziv());
        txtOpstina.setEditable(false);
        cmbUlica.setEnabled(false);
        cmbMesto.setEnabled(false);

        fillCmbZaposlenost();
        fillCmbGrad();

        cmbZaposlenost.setSelectedItem(delegat.getZaposlenostStatus());
        cmbMesto.setSelectedItem(delegat.getBroj().getUlica().getMesto());
        cmbUlica.setSelectedItem(delegat.getBroj().getUlica());

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parent.setEnabled(true);
                parent.reloadTable();
                dispose();
            }
        });
    }

    private void fillCmbZaposlenost() {
        cmbZaposlenost.setModel(new DefaultComboBoxModel<>(ZaposlenostStatusEnum.values()));
        cmbZaposlenost.setSelectedIndex(-1);
    }

    private void fillCmbGrad() {
        List<Mesto> gradovi = new ArrayList<>();

        try {
            gradovi = Controller.getInstance().getMesto(new Mesto());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        cmbMesto.setModel(new DefaultComboBoxModel<>(gradovi.toArray(new Mesto[0])));
        cmbMesto.setSelectedIndex(-1);

        cmbMesto.addActionListener(e -> {
            Mesto selektovano = (Mesto) cmbMesto.getSelectedItem();
            if (selektovano != null && selektovano.getOpstina() != null) {
                txtOpstina.setText(selektovano.getOpstina().getNaziv());

                fillCmbUlica(selektovano);
            }
        });

        cmbUlica.addActionListener(e -> {
            if (cmbUlica.getSelectedIndex() != -1) {
                addUlicaBtn.setEnabled(true);
            } else {
                addUlicaBtn.setEnabled(false);
            }
        });
    }

    private void fillCmbUlica(Mesto selektovano) {
        List<Ulica> ulice = new ArrayList<>();
        try {
            Ulica ulica = new Ulica();
            ulica.setMesto(selektovano);

            ulice = Controller.getInstance().getUlicaWithMestoCondition(ulica);

            cmbUlica.setModel(new DefaultComboBoxModel<>(ulice.toArray(new Ulica[0])));
            cmbUlica.setSelectedIndex(-1);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        if (ulice == null || ulice.isEmpty()) {
            addUlicaBtn.setEnabled(true);
        }
    }

    public void reloadUlice(Mesto selektovano) {
        fillCmbUlica(selektovano);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUlicaBtn;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbMesto;
    private javax.swing.JComboBox cmbUlica;
    private javax.swing.JComboBox cmbZaposlenost;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBroj;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtJmbg;
    private javax.swing.JTextField txtOpstina;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
