/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.view;

/**
 *
 * @author user
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        doc = new javax.swing.JMenu();
        itemUgovori = new javax.swing.JMenuItem();
        itemRasporedi = new javax.swing.JMenuItem();
        itemIzvestaji = new javax.swing.JMenuItem();
        itemSastavi = new javax.swing.JMenuItem();
        itemUtakmice = new javax.swing.JMenuItem();
        org = new javax.swing.JMenu();
        itemDelegati = new javax.swing.JMenuItem();
        itemSudije = new javax.swing.JMenuItem();
        itemEkipe = new javax.swing.JMenuItem();
        itemIgraci = new javax.swing.JMenuItem();
        itemHale = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setToolTipText("");

        doc.setText("Dokumenta");

        itemUgovori.setText("Ugovori");
        itemUgovori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUgovoriActionPerformed(evt);
            }
        });
        doc.add(itemUgovori);

        itemRasporedi.setText("Rasporedi");
        doc.add(itemRasporedi);

        itemIzvestaji.setText("Izvestaji");
        doc.add(itemIzvestaji);

        itemSastavi.setText("Sastavi ekipa");
        doc.add(itemSastavi);

        itemUtakmice.setText("Utakmice");
        doc.add(itemUtakmice);

        jMenuBar1.add(doc);

        org.setText("Organizacija");

        itemDelegati.setText("Delegati");
        itemDelegati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDelegatiActionPerformed(evt);
            }
        });
        org.add(itemDelegati);

        itemSudije.setText("Sudije");
        org.add(itemSudije);

        itemEkipe.setText("Ekipe");
        org.add(itemEkipe);

        itemIgraci.setText("Igraci");
        org.add(itemIgraci);

        itemHale.setText("Hale");
        org.add(itemHale);

        jMenuBar1.add(org);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUgovoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUgovoriActionPerformed
        new UgovoriForm(this).setVisible(true);
    }//GEN-LAST:event_itemUgovoriActionPerformed

    private void itemDelegatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDelegatiActionPerformed
        new DelegatiForm(this).setVisible(true);
    }//GEN-LAST:event_itemDelegatiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu doc;
    private javax.swing.JMenuItem itemDelegati;
    private javax.swing.JMenuItem itemEkipe;
    private javax.swing.JMenuItem itemHale;
    private javax.swing.JMenuItem itemIgraci;
    private javax.swing.JMenuItem itemIzvestaji;
    private javax.swing.JMenuItem itemRasporedi;
    private javax.swing.JMenuItem itemSastavi;
    private javax.swing.JMenuItem itemSudije;
    private javax.swing.JMenuItem itemUgovori;
    private javax.swing.JMenuItem itemUtakmice;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu org;
    // End of variables declaration//GEN-END:variables
}
